// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationCountController from "./notification_count_controller"
application.register("notification-count", NotificationCountController)

import TwemojiController from "./twemoji_controller"
application.register("twemoji", TwemojiController)
