// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import ContentWarningController from "./content_warning_controller"
application.register("content-warning", ContentWarningController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DialogToggleController from "./dialog_toggle_controller"
application.register("dialog-toggle", DialogToggleController)

import DidSwitchRemapperController from "./did_switch_remapper_controller"
application.register("did-switch-remapper", DidSwitchRemapperController)

import NotificationCountController from "./notification_count_controller"
application.register("notification-count", NotificationCountController)

import PopperController from "./popper_controller"
application.register("popper", PopperController)

import SkeetCompactController from "./skeet_compact_controller"
application.register("skeet-compact", SkeetCompactController)

import TwemojiController from "./twemoji_controller"
application.register("twemoji", TwemojiController)
