// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarLineController from "./avatar_line_controller"
application.register("avatar-line", AvatarLineController)

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import ContentWarningController from "./content_warning_controller"
application.register("content-warning", ContentWarningController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DialogToggleController from "./dialog_toggle_controller"
application.register("dialog-toggle", DialogToggleController)

import InfiniteScrollingController from "./infinite_scrolling_controller"
application.register("infinite-scrolling", InfiniteScrollingController)

import NotificationCountController from "./notification_count_controller"
application.register("notification-count", NotificationCountController)

import PopperController from "./popper_controller"
application.register("popper", PopperController)

import ScrollAnchorController from "./scroll_anchor_controller"
application.register("scroll-anchor", ScrollAnchorController)

import SubtleLinkController from "./subtle_link_controller"
application.register("subtle-link", SubtleLinkController)

import TwemojiController from "./twemoji_controller"
application.register("twemoji", TwemojiController)
